## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_module('logging', ['internet', 'config-store', 'stats'])
    obj.source = ["model/%s" % s for s in [
       'logging.cc',
       'node-probe.cc',
        ]]
    obj.source.append("helper/logging-helper.cc")

    module_test = bld.create_ns3_module_test_library('logging')
    module_test.source = [ ]

    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #   'test/flow-monitor-examples-test-suite.cc',
            ])
    
    headers = bld(features='ns3header')
    headers.module = 'logging'
    headers.source = ["model/%s" % s for s in [
       'logging.h',
       'node-probe.h',
        ]]
    headers.source.append("helper/logging-helper.h")

    if bld.env['ENABLE_EXAMPLES']:
        bld.recurse('examples')

    bld.ns3_python_bindings()
